### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by kaizadp** [PNNL-TES/3soils_2019#2]
###  **FTICR**

- [ ] Van-Krevelens
- [ ] relative abundance of groups
- [ ] new/lost molecules for each treatment
- [ ] unique molecules for each treatment?
- [ ] abundance of aromatic molecules
- [ ] Kendrick mass?
